apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pi-hole
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`pi-hole.home.arpa`)
    kind: Rule
    services:
    - name: pi-hole # must match Service name
      port: 80
  tls: {}
