apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-pvc
  namespace: pi-hole
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: truenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi
