apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  # TODO: Replace with TrueNAS storage once ready.
  # This temporary path stores Pi-hole gravity.db and config.
  hostPath:
    path: /mnt/data/pihole
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pi-hole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: pi-hole
