#cloud-config
autoinstall:
  version: 1

  # System identity
  identity:
    hostname: kube-node # Temporary hostname; replaced dynamically later
    username: Spar

  # Keyboard Layout
  keyboard:
    layout: us
  locale: en_US.UTF-8

  # Automatically configure network via DHCP
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: true # Let the router assign an IP automatically
        dhcp6: false

  storage:
    layout:
      name: lvm
  packages:
  - vim
  - htop
  - curl
  - docker.io
  - kubelet
  - kubeadm
  - kubectl
  # Commands to run after OS installation but before reboo
  late-commands:
  # Enable Docker service
  - curtin in-target --target=/target -- systemctl enable docker
  - curtin in-target --target=/target -- systemctl start docker

  # Prevent unwanted package upgrades for Kubernetes components
  - curtin in-target --target=/target -- apt-mark hold kubelet kubeadm kubectl

  # Dynamically assign a unique hostname based on the node's IP
  # Example: if IP = 192.168.50.101 → hostname = kube-node-101
  - curtin in-target --target=/target bash -c ' IP_LAST_OCTET=$(ip -4 addr show eth0 | grep -oP "(?<=inet\s)\d+\.\d+\.\d+\.\d+" | cut -d"." -f4) NEW_HOSTNAME="kube-node-${IP_LAST_OCTET}" echo "${NEW_HOSTNAME}" > /target/etc/hostname sed -i "s/127.0.1.1.*/127.0.1.1 ${NEW_HOSTNAME}/" /target/etc/hosts hostnamectl set-hostname "${NEW_HOSTNAME}" '
  # Automatically reboot after installation completes
  reboot: true
