apiVersion: v1
kind: Secret
metadata:
  name: pi-hole-secret
  namespace: pi-hole
type: Opaque
data:
  # Example: Base64 encoded password 'correct! horse0 battery staple1'
  FTLCONF_webserver_api_password: 'Y29ycmVjdCEgaG9yc2UwIGJhdHRlcnkgc3RhcGxlMQ=='
