# =========================================================
# Traefik IngressRoute
# =========================================================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ingress
  namespace: paperless
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`paperless.home.arpa`)
    kind: Rule
    services:
    - name: paperless-service
      port: 8000
  tls: {}
