# =========================================================
# PV for Paperless data
# =========================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/paperless-data
    type: DirectoryOrCreate
---

# =========================================================
# PV for backup storage
# =========================================================
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-paperless-backup
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /mnt/data/paperless-backup
#     type: DirectoryOrCreate


# =========================================================
# Persistent Volumes and Claims
# =========================================================
# PVC for Paperless document storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
---

# PVC for backups
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: paperless-backup-pvc
#   namespace: paperless
# spec:
#   accessModes: [ "ReadWriteOnce" ]
#   resources:
#     requests:
#       storage: 20Gi
---
