# =========================================================
# PV for PostgreSQL database
# =========================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/paperless-db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-pvc
  namespace: paperless
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
