apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: truenas-nfs-csi
  resources:
    requests:
      storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: paperless-data-pv
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: truenas-nfs-csi
#   claimRef:
#     namespace: paperless
#     name: paperless-data-pvc # Bind to specific PVC
#   nfs:
#     server: 192.168.4.50
#     path: /mnt/TrueNAS/k8s/paperless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-pvc
  namespace: paperless
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: paperless-db-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-db-pv
  namespace: paperless
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: paperless
    name: paperless-db-pvc # Bind to specific PVC
  volumeMode: Filesystem
  iscsi:
    targetPortal: 192.168.4.50:3260
    iqn: iqn.2005-10.org.freenas.ctl:postgres-paperless
    lun: 0
    fsType: ext4
    readOnly: false
