apiVersion: v1
kind: Namespace
metadata:
  name: homarr
  labels:
    name: homarr
    app: homarr
---
apiVersion: v1
kind: Service
metadata:
  name: homarr-service
  namespace: homarr
spec:
  type: ClusterIP
  selector:
    app: homarr
  ports:
  - protocol: TCP
    port: 7575
    targetPort: 7575
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-pvc
  namespace: homarr
spec:
  storageClassName: truenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      serviceAccountName: homarr
      containers:
      - name: homarr
        image: ghcr.io/homarr-labs/homarr:v1.45.1
        ports:
        - containerPort: 7575
        envFrom:
        - secretRef:
            name: homarr-secret
        volumeMounts:
        - name: homarr-data
          mountPath: /appdata
      imagePullSecrets:
      - name: ghcr-secret
      volumes:
      - name: homarr-data
        persistentVolumeClaim:
          claimName: homarr-pvc
