apiVersion: v1
kind: ServiceAccount
metadata:
  name: homarr
  namespace: homarr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homarr-read
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs: [ "get", "list", "watch" ]

- apiGroups: [ "networking.k8s.io" ]
  resources:
  - ingresses
  verbs: [ "get", "list", "watch" ]

- apiGroups: [ "apps" ]
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homarr-binding
subjects:
- kind: ServiceAccount
  name: homarr
  namespace: homarr
roleRef:
  kind: ClusterRole
  name: homarr-read
  apiGroup: rbac.authorization.k8s.io
