apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      serviceAccountName: homarr
      containers:
      - name: homarr
        image: ghcr.io/homarr-labs/homarr:v1.45.1
        ports:
        - containerPort: 7575
        envFrom:
        - secretRef:
            name: homarr-secretv2
        volumeMounts:
        - name: homarr-data
          mountPath: /appdata
      imagePullSecrets:
      - name: ghcr-secret
      volumes:
      - name: homarr-data
        persistentVolumeClaim:
          claimName: homarr-pvc
