apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: jellyfin
spec:
  storageClassName: truenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
