apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.4.203
  selector:
    app: jellyfin
  ports:
  - name: jellyfin-https
    protocol: TCP
    port: 8920
    targetPort: 8920
  - name: jellyfin-http
    protocol: TCP
    port: 8096
    targetPort: 8096
  - name: jellyfin
    protocol: UDP
    port: 7359
    targetPort: 7359
