
apiVersion: v1
kind: Namespace
metadata:
  name: redis

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 10Gi  # Adjust based on your expected cache size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/redis  # Path on host/NAS
    type: DirectoryOrCreate

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1  # Start with single instance; scale later if needed
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine  # Lightweight, stable Redis image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379  # Default Redis port
          env:
            # Optional: set Redis password via secret for secure access
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          command:
            - "redis-server"
            - "--requirepass"  # Enables password authentication
            - "$(REDIS_PASSWORD)"
            - "--save"      # Disable persistence if you want purely in-memory cache
            - "--appendonly no"  # Optional: disable AOF persistence
          volumeMounts:
            - name: redis-data
              mountPath: /data  # Redis persistence directory (optional)
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
# --------------------------------------------
# 5. Redis Service
# --------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  type: ClusterIP  # Internal access only; Jellyfin communicates internally
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
# --------------------------------------------
# 6. Redis Secret (optional, for password)
# --------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
data:
  # Example: Base64 encoded password 'correct! horse0 battery staple1'
  password: 'Y29ycmVjdCEgaG9yc2UwIGJhdHRlcnkgc3RhcGxlMQ=='
